version: '3'
services:
  frontend:
    build:
      context: './frontend'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: frontend-container
   
    networks:
      - mern-stack-network
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build:
      context: './backend'
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: backend-container
    networks:
      - mern-stack-network
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-container
    networks:
      - mern-stack-network
    volumes:
      - mongoData:/data/db
    env_file:
      - ./.env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=infra-todo
    #   - MONGO_INITDB_ROOT_PASSWORD=Infra2023
    #   - MONGO_INITDB_DATABASE=todo_db
networks:
  mern-stack-network:
volumes:
  mongoData: